modLoader="javafml"
loaderVersion="[4,)" # актуальный диапазон для NeoForge, при необходимости уточни
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
Port of Enchancement to NeoForge 1.21.1
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
